-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 41.461 s <<< FAILURE! - in TestSuite
FirstTestCase(Flows.LoginLogout2)  Time elapsed: 0.202 s  <<< FAILURE!
java.lang.AssertionError: Assertion Inside Catch expected [true] but found [false]
	at Flows.LoginLogout2.FirstTestCase(LoginLogout2.java:26)

